[package]
name = "rattletrap"
version = "0.1.0"
edition = "2024"

[dependencies]
winit = { version = "0.30.12", features = ["android-native-activity"] }
physics = { path = "physics" }
rhi = { path = "rhi" }
anyhow = "1.0.100"
image = "0.25.9"
bytemuck = "1.24.0"
include_bytes_aligned = "0.2.0"
glam = { version = "0.30.9", features = ["bytemuck"] }
regex = "1.12.2"
hashbrown = "0.16.1"
getset = "0.1.6"
